### ISSUE TITLE
Improvment: Newline for every signal when initing a module 

### ISSUE THREAD

**Issue by maor1993** [TheClams/SmartVHDL#10]
Just a pet peeve, would be nice if it was configurable :)

**Comment by TheClams** [comment]
Not sure I understand what you mean, can you provide an example ?

**Comment by maor1993** [comment]
Yes,

If for a example we have the following entity in another file:


entity case1 is
port(
 input1:..
input2:...
input3...

);

when you run init module and some of the signals are not present, it will generate a line like this:

signal input1... ; signal input2...; signal input3...;

instead of:
signal input1...;
signal input2...;
signal input3....;

its a small annoyance but since I use the init module feature a lot, me and the return key have become good friends...

**Comment by TheClams** [comment]
Ah ok it's a bug :P will be fixed soon
