### ISSUE TITLE
Constants in Blocks

### ISSUE THREAD

**Issue by rickydtran** [TheClams/SmartVHDL#15]
Having a constant or signal, maybe variable declared within a block statement highlights the the label of the block even though this is legal

stimulus_blk : block
  constant blah : time := 2 ns;
  signal rst blah2 : std_logic ;
begin
  process1
  process2
  ...
end block stimulus_blk; (Highlighed label)

**Comment by rickydtran** [comment]
Also when the "then" keyword is used, a drop down menu is generated which matches with the term "technical" for some reason, so if a if () then<enter> statement is written then "then" gets changed to the keyword technical.

Thanks for the great package btw

**Comment by TheClams** [comment]
The block issue is fixed in 1.4.1

What you see when you type then is basic SublimeText autocompletion feature: to avoid it the best is to use the snippets for if statement (type if then tab) that will insert the then statement for you ;)
