### ISSUE TITLE
Color highlighting isn't applied to entities instantiated within blocks

### ISSUE THREAD

**Issue by ditek** [TheClams/SmartVHDL#18]
If an entity is instantiated within a `block`, color highlighting isn't applied properly to it. It works properly within `generate` blocks though.

![image](https://user-images.githubusercontent.com/10835824/44350955-f069fa80-a4a0-11e8-9aa8-b61c2aa647da.png)

This is the case regardless of the theme being used.

**Comment by TheClams** [comment]
Fixed in 1.5.1

And next time, please copy the text instead of a picture, it is a lot easier for me to reproduce the issue with text ;)
