### ISSUE TITLE
Color Highlighting within Blocks

### ISSUE THREAD

**Issue by rickydtran** [TheClams/SmartVHDL#19]
stim_blk : block
        -- Generate 100 MHz System clock
        gen_sys_clk : process
        begin
            clk_sys <= '0', '1' after (CLK_SYS_PERIOD / 2);
            wait for (CLK_SYS_PERIOD);
        end process gen_sys_clk;
end block stim_blk;

It looks like color highlighting for a process with a label within a block doesn't quite work correctly

**Comment by TheClams** [comment]
Fixed in 1.5.3
