### ISSUE TITLE
Clickable hierarchy results

### ISSUE THREAD

**Issue by covex** [TheClams/SmartVHDL#2]
RFE: Would it be possible to make the results of show hierarchy clickable so that it leads to entity and architecture of the block?

**Comment by TheClams** [comment]
I added a function that you can now bind to a key or mouse click, but Sublime does not support context for mouse binding, contrary to key-binding: this means that binding a click to a function override every other click behavior ... 

I gave an example in the change log on how to bind the function to ctrl+right click which has no binding by default. 

If you need the binding to coexist with other normal behavior you will need to write a dedicated plugin (very simple) that choose the correct command depending on the scope.
