### ISSUE TITLE
Feature: add instances lookup

### ISSUE THREAD

**Issue by maor1993** [TheClams/SmartVHDL#7]
would be nice to have an instance lookup, where uses of the entity are listed when hovering over an entity.

**Comment by TheClams** [comment]
I implemented a function to retrieve all instance of an entity, but I did not put it in the pop-up for performances issues.
There is new features in the dev version of ST3 that might be fast enough to display directly on hover, but I need time to explore this.

**Comment by maor1993** [comment]
Hey @TheClams .
Is there a way to connect this to hover now?

**Comment by TheClams** [comment]
Yes, I already used it in the SystemVerilog Package, and it weems to work fine, I'll add it this week-end.
