### ISSUE TITLE
Symbol Search is broken

### ISSUE THREAD

**Issue by jimmyjon711** [TheClams/SmartVHDL#8]
I can no longer search for generates, entities, etc in symbol search. This looks like it changed going from version 1.1.3 to 1.2.0.

**Comment by jimmyjon** [comment]
Also I am using version 3114 which breaks the Package Control->Settings

**Comment by TheClams** [comment]
I checked with a clean install of 3114, and I can see the generate/entity in symbol search, and the menu to control settings works.
Do you see any error in the console ? And are you sure you don't have a plugin overriding mine ?

**Comment by jimmyjon** [comment]
Don't think that I have any other plugins that would be overriding yours. The only plugins that I have installed are SmartVhdl, Package Control, SystemVerilog and LatexTools. 

Also to note I am working on a linux machine Red Hat 6

I was playing around with the symbol list files and I can get it working if I put the strings all on one line like you once had it.

**Comment by TheClams** [comment]
Ok might be related to linux then, I'll try to set a VM to check that

**Comment by jimmyjon** [comment]
Also this is what I see when trying to select the settings
![settings](https://user-images.githubusercontent.com/6913701/34062567-702c26d6-e1aa-11e7-97d7-bdba345cac71.png)

**Comment by TheClams** [comment]
I managed to reproduce the symbol issue on linux: it might actually be a bug in ST, but anyway keeping everything on the same line works, so I'll let it like that.
For the settings issue I did not manage to reproduce it: did you try on a fresh install of sublime ?
